### ISSUE TITLE
NvgSharp.Renderer.DeleteTexture is unimplemented, causing `NvgContext.Dispose` to throw exceptions.

### ISSUE THREAD

**Issue by redxdev** [rds1983/NanoVGSharp#2]
`NvgContext` can't be disposed of properly as `NvgContext.Dispose()` calls `Renderer.DeleteTexture()` which throws `NotImplementedException()`.

https://github.com/rds1983/NvgSharp/blob/4964312f1440dc5bb5e41c9286041e3af1cb8bc6/src/NvgSharp/Renderer.cs#L115

**Comment by rds1983** [comment]
Fixed, thanks for noticing!
