### ISSUE TITLE
unknown function from the current nuget release

### ISSUE THREAD

**Issue by xarthurx** [rds1983/NanoVGSharp#7]
When compiling from the source, samples work correctly.

However, if I install `NvgSharp` from `nuget` and use it in other projects, I got the following errors with a similar setup as the sample project:
![image](https://user-images.githubusercontent.com/1921878/224015772-f9bde0b8-46e6-4392-9be2-a54fc3be4e8d.png)

I checked the code and it seems the error is caused by the additional code pushed after the `nuget` package was released.

Would it be possible to release a new update to the `nuget` package?

**Comment by rds1983** [comment]
Thanks for noticing.
Released new version 0.6.3
